name: Build

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Windows

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Artifact Upload
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v2
        with:
          name: "windows"
          path: ./target/release/erl.exe
  build-ubuntu:
    runs-on: ubuntu-latest
    name: Build Ubuntu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Artifact Upload
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v2
        with:
          name: "ubuntu"
          path: ./target/release/erl

