name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        target: ["aarch64-unknown-linux-musl", "aarch64-pc-windows-msvc"]

    runs-on: windows-latest
    name: Build for ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }}

          name: Build
